### ISSUE TITLE
Showing below error

### ISSUE THREAD

**Issue by Shanmugam031093** [jadhavpritish/Dream11_Predictor#1]
Traceback (most recent call last):
  File "E:\oldd\Compressed\Dream11_Predictor-master\Dream11_Predictor-master\src\player_selection_dream11.py", line 14, in <module>
    import pulp
ModuleNotFoundError: No module named 'pulp'

**Comment by pritishperpetua** [comment]
@Shanmugam031093  - You will have to install PuLP .

run command `pip install pulp` from your terminal. 

for more info - 
1. [installing PuLP](https://pypi.org/project/PuLP/)
2. [Using PuLP](https://coin-or.github.io/pulp/) 

Hope this helps.

**Comment by Shanmugam031093** [comment]
Thanks for your reply bro but still error has not solved , see below
showing error

Traceback (most recent call last):
  File
"C:\Users\Shanmugam\Desktop\Dream11_Predictor-master\src\player_selection_dream11.py",
line 151, in <module>
    print('Status:', LpStatus[prob.status])
NameError: name 'LpStatus' is not defined

**Comment by jadhavpritish** [comment]
This is an older version and perhaps needs a few tweaks..
I would recommend you to take a look at this [article](https://jadhavpritish.github.io/fantasy_sports_auto_selection.html) that is more mature than the code in this repo

**Comment by Shanmugam031093** [comment]
Hi bro

Could you please send updated python file as attachment and then tell me if
you have any social accounts...I would like to follow...

Regards
Shanmugam R

**Comment by Shanmugam031093** [comment]
> @Shanmugam031093 - You will have to install PuLP .
> 
> run command `pip install pulp` from your terminal.
> 
> for more info -
> 
> 1. [installing PuLP](https://pypi.org/project/PuLP/)
> 2. [Using PuLP](https://coin-or.github.io/pulp/)
> 
> Hope this helps.

**Comment by jadhavpritish** [comment]
@Shanmugam031093 - I will update the repo sometime this weekend with sample data and everything.

you can connect with me via [linkedin](https://www.linkedin.com/in/pritish-sunil-jadhav-537075a4/)

**Comment by Shanmugam031093** [comment]
Hi Bro,

Thank you very much for your reply, I am waiting for you.

Regards
Shanmugam R

**Comment by Shanmugam031093** [comment]
Hi Bro,

Sorry for the distubance, Any updates for above mail

Regards
Shanmugam R

**Comment by jadhavpritish** [comment]
@Shanmugam031093 - I have updated the repo. Please follow the readme file for successfully running the code.Hope it helps.

**Comment by Shanmugam031093** [comment]
thanks bro, one more help where do i get last five match points is there
any websites

Regards
Shanmugam
