### ISSUE TITLE
error

### ISSUE THREAD

**Issue by romilxz** [jadhavpritish/Dream11_Predictor#3]
### shows following error
`Traceback (most recent call last):
  File "src/player_selection_dream11.py", line 223, in <module>
    caller(args.player_data_filepath)
  File "src/player_selection_dream11.py", line 148, in caller
    if not os.path.exists(filepath):
  File "C:\pythonn\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`

**Comment by vinit7801** [comment]
Getting same error

**Comment by jadhavpritish** [comment]
can you copy paste the command that you are running from the terminal ?

cc: @vinit7801 @romilxz

**Comment by vinit7801** [comment]
pipenv run python src/player_selection_dream11.py

**Comment by jadhavpritish** [comment]
you need to run the command - 

`pipenv run python src/player_selection_dream11.py --player_data_filepath <absolute_data_filepath>`

where <absolute_data_filepath> is the filepath of the csv containing raw data. You can find a sample file in the data folder. 

hope this helps.

**Comment by vinit7801** [comment]
pipenv run python src/player_selection_dream11.py --player_data_filepath <C:\\Users\\User\\Dream11_Predictor\\data>

it says syntax of the command  is incorrect

**Comment by jadhavpritish** [comment]
you dont have to use `<` and `>`. They are used to indicate that `absolute_file_path` is a place holder. 

in our case, please try running . You may have to add quotes around 
`pipenv run python src/player_selection_dream11.py --player_data_filepath C:\\Users\\User\\Dream11_Predictor\\data\\dream11_performance_data.csv`

**Comment by vinit7801** [comment]
just one last issues it reads the csv files 
but then how does it helps in dream 11 prediction?

**Comment by jadhavpritish** [comment]
Given a data file (you have to design it manually currently), the module tells you the team to be picked.

Check the output that is printed on the terminal. I will try to post a screenshot soon.

**Comment by vinit7801** [comment]
ok thanks got the whole model just wanted to know where to find dream 11 last five scores?

**Comment by jadhavpritish** [comment]
You may want to read the blog - `https://jadhavpritish.github.io/fantasy_sports_auto_selection.html` for a better understanding....


Note- 
The blog and code is primarily meant for highlighting the use of data science in fantasy sports. I DO NOT guarantee 100% success ratio.

**Comment by vinit7801** [comment]
hey thanks got it thought it would use multivariable linear Regression...but it uses Integer Linear Programming 
just wanted to know any sites from where you can get dream 11 scores which is very important for this model

**Comment by jadhavpritish** [comment]
That is the catch, you will have to use dream11 app to fill out the csv.

A more ideal solution would be to -

1. Get data directly from dream11 via API (if they provide an API)
2. If dream11 does not have an API, we will have to get the data from espncricinfo or cricbuzz via API and convert them into points using dream11 point system.
https://www.dream11.com/games/point-system

**Comment by vinit7801** [comment]
but how do you convert say fielding points into real points

**Comment by jadhavpritish** [comment]
How to use espncricinfo data to compute dream11 points-

1. Get the data for number of catches taken, run-outs , wkts and runs for all players
2. Convert runs, wkts , run-outs, catches to fantasy points using dream11s conversion table.
3. Dump the data structure to a csv and plumb it with the linear programming script.

For now you can create the csv file manually using dream11 app. It is super time consuming but will get the job done.

**Comment by vinit7801** [comment]
just final question does it work on football as well
and why weighted average of 5 isnt it too little of a sample size?

**Comment by romilxz** [comment]
@jadhavpritish bro please make a video .
so it will be helpful for others too.
and also how to increase the sample size 
obviously as @vinit7801 has said that the 5 sample size is too small for prediction.

**Comment by romilxz** [comment]
![image](https://user-images.githubusercontent.com/65399150/96790337-41c0fc00-1414-11eb-9473-e88a60c14c4a.png)

**Comment by jadhavpritish** [comment]
1. It won't work out of the box for football because the constraints are different and definitions are different. But it is not super hard to add code to handle football data as well.

2. Feel free to use more data. I chose 5 arbitarily.

**Comment by vinit7801** [comment]
and there is one issues of no prediction on who to should you choose as cap and vc
should you choose based on weighted_player_points?

**Comment by jadhavpritish** [comment]
Apologies for the delayed response. Yes. the choice of C and VC is not a part of the current code. It is currently out-of-scope.
